### ISSUE TITLE
Add id column for easier file retrieval

### ISSUE THREAD

**Issue by shoeper** [telekom-security/smbwatch#5]
Das Hinzufügen einer id kann genutzt werden um z.B. mittels eines Skriptes einzelne Dateien herunterzuladen. Aktuell muss dazu erst eine ID hinzugefügt werden. Dann kann z.B. mittels DB Browser for SQLite die Datenbank untersucht werden und einzelne Dateien können über die ID vom Ziel abgerufen werden. Der Abruf auf Anfrage könnte auch direkt in smbwatch integriert werden.

Hinzufügen einer id (ja alle Daten sind dann erstmal doppelt vorhanden)

```
CREATE TABLE files_id (
    id integer primary key autoincrement, 
    server text,
    sharename text,

    name text,
    path text,
    extension text,

    size int,
    modified_at datetime,
    mode int);

INSERT INTO files_id(server, sharename, name, path, extension,size, modified_at,mode)
SELECT server, sharename, name, path, extension,size, modified_at,mode
FROM files;
```

Script to fetch file

fetch.sh <id>
```
#!/bin/bash
# yes this is a little ugly

domain=
user=
password=
db="sqlite.db"
tmpdir=tmp

server=`sqlite3 "$db" "SELECT server FROM files_id WHERE id=$1;"`
sharename=`sqlite3 "$db" "SELECT sharename FROM files_id WHERE id=$1;"`
path=`sqlite3 "$db" "SELECT path FROM files_id WHERE id=$1;" | tr '\' '/'`
name=`sqlite3 "$db" "SELECT name FROM files_id WHERE id=$1;"`

if [[ "$path" == "." ]]
then
	path=""
fi

mkdir -p "$tmpdir"
echo "smbget -U \"$domain/$user%$password\" 'smb://$server/$sharename/$path/$name'" >&2

cd "$tmpdir"
smbget -U "$domain/$user%$password" "smb://$server/$sharename/$path/$name"

cat "'$tmpdir/$name'"
```

**Comment by rverton** [comment]
Hallo @shoeper,
sqlite nutzt einen impliziten Primary Key mit dem Namen `rowid`, außer die Tabelle wird mit `without rowid` angelegt. Wenn manuell ein (numerischer) Primary Key angelegt wird, ist dies auch nur ein alias auf die schon vorhandene rowid.

Es kann also jetzt schon per ID abgerufen werden, dafür kann im DB Browser explizit die `rowid` mit abgerufen werden:
1. `select *, rowid from foo`
2. *rowid* merken für das `fetch.sh` skript
3. Mit `select * from foo where rowid=?` den entsprechenden Eintrag abrufen

**Comment by shoeper** [comment]
@rverton Danke. Ist tatsächlich viel einfacher. Neben der Query kann DB Browser for SQLite diese auch einfach generieren (unter Tools -> Show Row Counts).
